# gitleaks.toml - Simplified for debugging

title = "Gitleaks simplified configuration"

[[rules]]
id = "generic-api-key"
description = "Generic API Key"

regex = '''(?i)api_key\s*=\s*['"](.{20,})['"]'''
tags = ["key", "API"]