name: 'Test Local Action'

on:
  push:


jobs:
  test-self-hosted-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create fake secret file for testing
        run: |
          echo "api_key2 = 'apikey2" > test-secrets.txt

      - name: Run Secrets Vault Scanner
        uses: ./
        with:
          vault_provider: 'self-hosted'
          self_hosted_vault_url: ${{ secrets.VAULT_URL }}
          self_hosted_vault_api_key: ${{ secrets.VAULT_API_KEY }}