name: 'Test Local Action'

on:
  push:
    branches:
      - main

jobs:
  test-self-hosted-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # THIS IS THE MISSING STEP
      - name: Create fake secret file for testing
        run: |
          echo "api_key = 'a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0_fake'" > test-secrets.txt

      - name: Run Secrets Vault Scanner
        uses: ./ 
        with:
          vault_provider: 'self-hosted'
          self_hosted_vault_url: ${{ secrets.VAULT_URL }}
          self_hosted_vault_api_key: ${{ secrets.VAULT_API_KEY }}